<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Customer;
use App\Models\CustomerGroup;
use App\Models\Salesman;
use App\Models\PaymentTerm;
use App\Models\PaymentMethod;
use App\Models\Address;
use App\Models\CustomerContact;
use App\Models\CustomerAttachment;
use App\Models\CustomerCreditLimit;
use App\Models\CustomerOpeningBalance;
use App\Models\Country;
use App\Models\Zone;
use App\Models\City;
use App\Models\Currency;
use Faker\Factory as Faker;
use Illuminate\Support\Arr;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        // Create a default customer group if none exists
        $customerGroup = CustomerGroup::firstOrCreate(
            ['name' => 'Default Group'],
            ['code' => 'DEFAULT', 'active' => true]
        );

        // Create a default salesman if none exists
        $salesman = Salesman::firstOrCreate(
            ['code' => 'DEFAULT'],
            [
                'name' => 'Default Salesman',
                'address' => $faker->address(),
                'phone1' => $faker->phoneNumber(),
                'phone2' => $faker->optional()->phoneNumber(),
                'email' => $faker->email(),
                'is_manager' => false,
                'is_supervisor' => false,
                'is_collector' => true,
                'fix_commission' => 0.00,
                'commission_percent' => 5.00,
                'commission_by_item' => 0.00,
                'commission_by_turnover' => 0.00,
                'active' => true
            ]
        );

        // Create a default payment term if none exists
        $paymentTerm = PaymentTerm::firstOrCreate(
            ['name' => 'Net 30'],
            [
                'nb_days' => 30,
                'active' => true
            ]
        );

        // Create a default payment method if none exists
        $paymentMethod = PaymentMethod::firstOrCreate(
            ['name' => 'Bank Transfer'],
            [
                'is_credit_card' => false,
                'active' => true
            ]
        );

        // Get some location IDs for addresses
        $countryId = Country::first()->id ?? 1;
        $zoneId = Zone::first()->id ?? 1;
        $cityId = City::first()->id ?? 1;

        // Create a default currency if none exists
        $currency = Currency::firstOrCreate(
            ['code' => 'USD'],
            [
                'name' => 'US Dollar',
                'iso_code' => 'USD',
                'rate' => 1.0000
            ]
        );

        // Create 10 sample customers
        for ($i = 0; $i < 10; $i++) {
            // Create addresses (billing and shipping)
            $billingAddress = Address::create([
                'address_line1' => $faker->streetAddress(),
                'city_id' => $cityId,
                'zone_id' => $zoneId,
                'zip_code' => $faker->postcode(),
                'country_id' => $countryId,
            ]);
            $shippingAddress = Address::create([
                'address_line1' => $faker->streetAddress(),
                'city_id' => $cityId,
                'zone_id' => $zoneId,
                'zip_code' => $faker->postcode(),
                'country_id' => $countryId,
            ]);

            // Create the customer (all fields)
            $customer = Customer::create([
                // Personal info
                'title' => Arr::random(['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.']),
                'first_name' => $faker->firstName(),
                'middle_name' => $faker->optional()->firstName(),
                'last_name' => $faker->lastName(),
                'display_name' => null, // will be generated by DB
                'company_name' => $faker->company(),
                'phone1' => $faker->phoneNumber(),
                'phone2' => $faker->optional()->phoneNumber(),
                'phone3' => $faker->optional()->phoneNumber(),
                'file_number' => $faker->unique()->numerify('FN####'),
                'bar_code' => $faker->unique()->ean13(),
                'search_terms' => $faker->words(3, true),
                // Business info
                'trade_id' => null,
                'company_code_id' => null,
                'customer_group_id' => $customerGroup->id,
                'business_type_id' => null,
                'sales_channel_id' => null,
                'distribution_channel_id' => null,
                'media_channel_id' => null,
                'indicator' => Arr::random(['A', 'B', 'C', 'D']),
                'risk_category' => Arr::random(['A', 'B', 'C', 'D']),
                // Salesmen
                'salesman_id' => $salesman->id,
                'collector_id' => $salesman->id,
                'supervisor_id' => $salesman->id,
                'manager_id' => $salesman->id,
                // Payment
                'payment_term_id' => $paymentTerm->id,
                'payment_method_id' => $paymentMethod->id,
                'allow_credit' => $faker->boolean(),
                'accept_cheque' => $faker->boolean(),
                'payment_day' => (string)rand(1, 30),
                'track_payment' => Arr::random(['yes', 'no']),
                'settlement_method' => Arr::random(['FIFO', 'Manual']),
                // Pricing
                'pricing_choice' => Arr::random(['price1', 'price2', 'price3', 'price4', 'price5', 'price6', 'last_invoice_price']),
                'discount_by_item' => $faker->randomFloat(2, 0, 10),
                'global_discount' => $faker->randomFloat(2, 0, 10),
                'discount_class' => Arr::random(['Silver', 'Gold', 'Platinum']),
                'markup_percentage' => $faker->randomFloat(2, 0, 10),
                'markdown_percentage' => $faker->randomFloat(2, 0, 10),
                // Tax
                'taxable' => $faker->boolean(),
                'tax_rate' => $faker->randomFloat(2, 0, 15),
                'tax_number' => $faker->optional()->numerify('TAX####'),
                'is_exempted' => $faker->boolean(10),
                'exemption_from' => $faker->optional()->word(),
                'exemption_reference' => $faker->optional()->word(),
                'exempted_from_date' => $faker->optional()->date(),
                'exempted_till_date' => $faker->optional()->date(),
                // Status
                'active' => true,
                'black_listed' => $faker->boolean(5),
                'one_time_account' => $faker->boolean(10),
                'special_account' => $faker->boolean(10),
                'pos_customer' => $faker->boolean(10),
                'free_delivery_charge' => $faker->boolean(10),
                'print_invoice_language' => Arr::random(['English', 'Arabic']),
                'send_invoice' => Arr::random(['email', 'sms', 'whatsapp', 'all']),
                // Messaging
                'add_message' => $faker->boolean(30),
                'invoice_message' => $faker->optional()->sentence(),
                // Primary contact (set below)
                'contacts_id' => null,
                // Notes
                'notes' => $faker->optional()->sentence(),
            ]);

            // Attach addresses via pivot
            $customer->addresses()->attach($billingAddress->id, [
                'address_type' => 'billing',
                'is_primary' => false,
                'address_name' => 'Main Billing',
                'notes' => $faker->optional()->sentence(),
            ]);
            $customer->addresses()->attach($shippingAddress->id, [
                'address_type' => 'shipping',
                'is_primary' => true,
                'address_name' => 'Main Shipping',
                'notes' => $faker->optional()->sentence(),
            ]);

            // Create and link a contact
            $contact = CustomerContact::create([
                'customer_id' => $customer->id,
                'title' => Arr::random(['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.']),
                'name' => $faker->name(),
                'work_phone' => $faker->optional()->phoneNumber(),
                'mobile' => $faker->optional()->phoneNumber(),
                'email' => $faker->optional()->email(),
                'position' => $faker->optional()->jobTitle(),
                'extension' => $faker->optional()->numerify('###'),
            ]);
            $customer->contacts_id = $contact->id;
            $customer->save();

            // Optionally: create an attachment
            CustomerAttachment::create([
                'customer_id' => $customer->id,
                'file_path' => 'attachments/sample.pdf',
                'file_name' => 'sample.pdf',
                'file_type' => 'pdf',
            ]);

            // Optionally: create a credit limit
            CustomerCreditLimit::create([
                'customer_id' => $customer->id,
                'currency_id' => $currency->id,
                'credit_limit' => $faker->numberBetween(1000, 10000),
                'used_credit' => 0,
                'available_credit' => $faker->numberBetween(1000, 10000),
                'is_active' => true,
                'notes' => $faker->optional()->sentence(),
            ]);

            // Optionally: create an opening balance
            CustomerOpeningBalance::create([
                'customer_id' => $customer->id,
                'currency_id' => $currency->id,
                'opening_amount' => $faker->numberBetween(1000, 10000),
                'opening_date' => $faker->date(),
                'notes' => $faker->optional()->sentence(),
                'is_active' => true,
            ]);
        }

        $this->command->info('Customers seeded successfully!');
    }
}
