<?php

namespace Database\Factories;

use App\Models\BusinessType;
use App\Models\CompanyCode;
use App\Models\CustomerGroup;
use App\Models\DistributionChannel;
use App\Models\MediaChannel;
use App\Models\MediaType;
use App\Models\PaymentMethod;
use App\Models\PaymentTerm;
use App\Models\Referrer;
use App\Models\SalesChannel;
use App\Models\Salesman;
use App\Models\Trade;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Arr;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Customer>
 */
class CustomerFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // Personal Information
            'title' => Arr::random(['Mr.', 'Mrs.', 'Ms.', 'Dr.', 'Prof.']),
            'first_name' => $this->faker->firstName(),
            'middle_name' => $this->faker->optional()->firstName(),
            'last_name' => $this->faker->lastName(),
            'display_name' => null, // will be generated by DB
            'company_name' => $this->faker->company(),
            'phone1' => $this->faker->phoneNumber(),
            'phone2' => $this->faker->optional()->phoneNumber(),
            'phone3' => $this->faker->optional()->phoneNumber(),
            'email' => $this->faker->optional()->email(),
            'card_number' => $this->faker->optional()->numerify('CARD####'),
            'date_of_birth' => $this->faker->optional()->date('Y-m-d', '2000-01-01'),
            'place_of_birth' => $this->faker->optional()->city(),
            'gender' => $this->faker->optional()->randomElement(['Male', 'Female', 'Other']),
            'blood_type' => $this->faker->optional()->randomElement(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']),
            'marital_status' => $this->faker->optional()->randomElement(['Single', 'Married', 'Divorced', 'Widowed', 'Other']),

            // Business Information
            'file_number' => $this->faker->unique()->numerify('FN####'),
            'bar_code' => $this->faker->unique()->ean13(),
            'search_terms' => json_encode($this->faker->words(3)),

            // Category
            'trade_id' => Trade::factory(),
            'company_code_id' => CompanyCode::factory(),
            'customer_group_id' => CustomerGroup::factory(),
            'business_type_id' => BusinessType::factory(),
            'sales_channel_id' => SalesChannel::factory(),
            'distribution_channel_id' => DistributionChannel::factory(),
            'media_channel_id' => MediaChannel::factory(),
            'media_type_id' => MediaType::factory(),
            'referral_id' => Referrer::factory(),
            'indicator' => Arr::random(['A', 'B', 'C', 'D']),
            'risk_category' => Arr::random(['Low', 'Medium', 'High']),

            // Salesmen
            'salesman_id' => Salesman::factory(),
            'collector_id' => Salesman::factory(),
            'supervisor_id' => Salesman::factory(),
            'manager_id' => Salesman::factory(),

            // Payment terms
            'payment_term_id' => PaymentTerm::factory(),
            'payment_method_id' => PaymentMethod::factory(),
            'allow_credit' => $this->faker->boolean(),
            'accept_cheques' => $this->faker->boolean(),

            // Pricing
            'price_choice' => Arr::random(['price1', 'price2', 'price3', 'price4', 'price5', 'price6', 'last_invoice_price']),
            'price_list' => Arr::random(['standard', 'premium', 'wholesale']),
            'global_discount' => $this->faker->randomFloat(2, 0, 10),
            'discount_class' => Arr::random(['Silver', 'Gold', 'Platinum']),
            'markup_percentage' => $this->faker->randomFloat(2, 0, 10),
            'markdown_percentage' => $this->faker->randomFloat(2, 0, 10),

            // Tax
            'taxable' => $this->faker->boolean(),
            'taxed_from_date' => $this->faker->optional()->date(),
            'taxed_till_date' => $this->faker->optional()->date(),
            'subjected_to_tax' => $this->faker->boolean(),
            'added_tax' => $this->faker->optional()->randomFloat(2, 0, 15),
            'exempted' => $this->faker->boolean(10),
            'exempted_from' => $this->faker->optional()->word(),
            'exemption_reference' => $this->faker->optional()->word(),
            'exempted_from_date' => $this->faker->optional()->date(),
            'exempted_till_date' => $this->faker->optional()->date(),

            // More details
            'active' => true,
            'black_listed' => $this->faker->boolean(5),
            'blacklisted_reason' => $this->faker->optional()->sentence(),
            'one_time_account' => $this->faker->boolean(10),
            'special_account' => $this->faker->boolean(10),
            'pos_customer' => $this->faker->boolean(10),
            'free_delivery_charge' => $this->faker->boolean(10),
            'print_invoice_language' => Arr::random(['English', 'Arabic']),
            'send_invoice' => Arr::random(['email', 'sms', 'whatsapp', 'all']),

            // Message functionality
            'showMessageField' => $this->faker->boolean(30),
            'message' => $this->faker->optional()->sentence(),

            // Primary contact reference
            'contacts_id' => null,

            'notes' => $this->faker->optional()->sentence(),
        ];
    }

    /**
     * Indicate that the customer is blacklisted.
     */
    public function blacklisted(): static
    {
        return $this->state(fn (array $attributes) => [
            'black_listed' => true,
            'blacklisted_reason' => $this->faker->sentence(),
        ]);
    }

    /**
     * Indicate that the customer is inactive.
     */
    public function inactive(): static
    {
        return $this->state(fn (array $attributes) => [
            'active' => false,
        ]);
    }

    /**
     * Indicate that the customer allows credit.
     */
    public function allowsCredit(): static
    {
        return $this->state(fn (array $attributes) => [
            'allow_credit' => true,
        ]);
    }

    /**
     * Indicate that the customer accepts cheques.
     */
    public function acceptsCheques(): static
    {
        return $this->state(fn (array $attributes) => [
            'accept_cheques' => true,
        ]);
    }

    /**
     * Indicate that the customer is taxable.
     */
    public function taxable(): static
    {
        return $this->state(fn (array $attributes) => [
            'taxable' => true,
            'subjected_to_tax' => true,
            'added_tax' => $this->faker->randomFloat(2, 5, 15),
        ]);
    }

    /**
     * Indicate that the customer is exempted from tax.
     */
    public function taxExempted(): static
    {
        return $this->state(fn (array $attributes) => [
            'taxable' => true,
            'exempted' => true,
            'exempted_from' => $this->faker->word(),
            'exemption_reference' => $this->faker->word(),
        ]);
    }
}
