<?php

namespace App\Enums;

enum PageCode: string
{
    case CUSTOMERS_GROUPS = 'CUSTOMERS_GROUPS';
    case CUSTOMERS_SALESMEN = 'CUSTOMERS_SALESMEN';
    case CUSTOMERS_CUSTOMERS = 'CUSTOMERS_CUSTOMERS';
    case CUSTOMERS_MASTER_LISTS = 'CUSTOMERS_MASTER_LISTS';
    case ITEMS_PRODUCT_LINES = 'ITEMS_PRODUCT_LINES';
    case ITEMS_CATEGORIES = 'ITEMS_CATEGORIES';
    case ITEMS_BRANDS = 'ITEMS_BRANDS';
    case ITEMS_ITEMS = 'ITEMS_ITEMS';
    case SERVICES_CATEGORIES = 'SERVICES_CATEGORIES';
    case SERVICES_SERVICES = 'SERVICES_SERVICES';
    case UNITS_GROUPS = 'UNITS_GROUPS';
    case UNITS_MEASUREMENTS = 'UNITS_MEASUREMENTS';

    case ADDRESS_CODES_COUNTRIES = 'ADDRESS_CODES_COUNTRIES';
    case ADDRESS_CODES_CITIES = 'ADDRESS_CODES_CITIES';
    case ADDRESS_CODES_DISTRICTS = 'ADDRESS_CODES_DISTRICTS';
    case ADDRESS_CODES_ZONES = 'ADDRESS_CODES_ZONES';

    case PAYMENT_TERMS = 'PAYMENT_TERMS';
    case PAYMENT_METHODS = 'PAYMENT_METHODS';

    case GENERAL_FILES_BUSINESS_TYPES = 'GENERAL_FILES_BUSINESS_TYPES';
    case GENERAL_FILES_SALES_CHANNELS = 'GENERAL_FILES_SALES_CHANNELS';
    case GENERAL_FILES_DISTRIBUTION_CHANNELS = 'GENERAL_FILES_DISTRIBUTION_CHANNELS';
    case GENERAL_FILES_MEDIA_CHANNELS = 'GENERAL_FILES_MEDIA_CHANNELS';

    case SECTIONS_PROJECTS = 'SECTIONS_PROJECTS';
    case SECTIONS_COST_CENTERS = 'SECTIONS_COST_CENTERS';
    case SECTIONS_DEPARTMENTS = 'SECTIONS_DEPARTMENTS';
    case SECTIONS_TRADES = 'SECTIONS_TRADES';
    case SECTIONS_COMPANY_CODES = 'SECTIONS_COMPANY_CODES';
    case SECTIONS_JOBS = 'SECTIONS_JOBS';

    case RELATIONS_ASSOCIATIONS = 'RELATIONS_ASSOCIATIONS';
    case RELATIONS_REFERRERS = 'RELATIONS_REFERRERS';
    case RELATIONS_MEDIA_TYPES = 'RELATIONS_MEDIA_TYPES';
    case SUPPLIERS_GROUPS = 'SUPPLIERS_GROUPS';
    case SUPPLIERS_SUPPLIERS = 'SUPPLIERS_SUPPLIERS';

    case SCHEDULER_PAGE = 'SCHEDULER_PAGE';
    case SYSTEM_SETTINGS_PAGE = 'SYSTEM_SETTINGS_PAGE';
    case PROFILE_PAGE = 'PROFILE_PAGE';

    case DASHBOARD_PAGE = 'DASHBOARD_PAGE';
    case DASHBOARD_OVERVIEW_PAGE = 'DASHBOARD_OVERVIEW_PAGE';
    case DASHBOARD_ANALYTICS_PAGE = 'DASHBOARD_ANALYTICS_PAGE';
    case DASHBOARD_REPORTS_PAGE = 'DASHBOARD_REPORTS_PAGE';

    case SUPPORT_HELP_PAGE = 'SUPPORT_HELP_PAGE';
    case SUPPORT_CONTACT_PAGE = 'SUPPORT_CONTACT_PAGE';

    case USER_MANAGEMENT_PAGE = 'USER_MANAGEMENT_PAGE';
    case PERMISSIONS_PAGE = 'PERMISSIONS_PAGE';
    case ROLES_PAGE = 'ROLES_PAGE';
}
